### ISSUE TITLE
Otel example

### ISSUE THREAD

**Issue by sluongng** [zoidyzoidzoid/gitlab-honeycomb-buildevents-webhooks-sink#8]
Hey thanks for creating/opensourcing/maintaining this project.

It inspired me to create my own https://github.com/sluongng/buildkite-honeycomb-exporter/ recently.

However over there I used Open Telemetry SDK so it's a bit more portable and therefore not locked-in to honeycomb and users can swapped out their tracing backend to any other Otel compatible vendor/services.

Just wana give you a ping just in case you ever need Otel example :D

**Comment by zoidyzoidzoid** [comment]
Awesome, thanks for linking!

I'll add a link to the README in case it helps folks discover it, since they're sort of related.

I wonder if it'd be easy enough to abstract it more to share one codebase, but maybe that'd be more of a headache than it'd be worth.
